#!/usr/bin/env python3
"""
    This script watches for sources and rebuild theme.json
"""

import json, yaml
import time
from random import choice as ch

import hashlib

from datetime import datetime
from os.path import splitext


class Theme:
    def __init__(self):

        self._file_palette = "src/palette.yaml"
        self._file_theme = "src/theme.yaml"
        self._file_tokens = "src/tokens.yaml"
        self._monitor = {}

        self.dest = "theme.json"

    def dpath(self, color_map, path):
        tmp = dict(color_map)

        for i in path.split("."):
            tmp = tmp.get(i, f"{path}")
            if isinstance(tmp, str):
                return tmp

        return tmp

    def pick(self, path):

        if path == '_':
            param_value = Theme.random_color()
        elif "/" in path:
            rgb, a = path.split("/")
            param_value = self.dpath(self._palette, rgb) + self.dpath(
                self._palette, a)
        elif "." in path:
            param_value = self.dpath(self._palette, path)
        elif path[0] == "#":
            param_value = path
        else:
            param_value = self.dpath(self._palette, path)

        return param_value

    def is_changed(self) -> bool:

        changed_theme = self._is_changed(self._file_theme)
        changed_tokens = self._is_changed(self._file_tokens)
        changed_palette = self._is_changed(self._file_palette)

        if changed_palette:
            self._palette = Theme.read(self._file_palette)
            print("Palette changed  : {0}".format(datetime.now().time()))

        if changed_tokens:
            self._tokens = Theme.read(self._file_tokens)
            print("Tokens changed   : {0}".format(datetime.now().time()))

        if changed_theme:
            self._theme = Theme.read(self._file_theme)
            print("Theme changed    : {0}".format(datetime.now().time()))

        return changed_palette or changed_theme or changed_tokens

    def _is_changed(self, file) -> bool:
        hasher = hashlib.md5()
        with open(file, "r") as f:
            buf = f.read()
            hasher.update(buf.encode())

        if self._monitor.get(file, None) == hasher.hexdigest():
            return False

        self._monitor[file] = hasher.hexdigest()
        return True

    def generate(self):
        t = Theme.read(self.dest)
        if not len(t):
            t = {
                "name": "Acid Night - Green",
                "type": "dark",
            }

        # Updating colors
        t['colors'] = {}

        if self._theme:
            for section, values in self._theme.items():

                if isinstance(values, dict):
                    for param, value in values.items():
                        # print(value)
                        name = f"{section}.{param}"
                        t['colors'][name] = self.pick(value)
                else:
                    t['colors'][f"{section}"] = self.pick(values)

        # updating tokens
        t['tokenColors'] = []
        if self._tokens:
            for item in self._tokens.get('scopes', []):
                if "settings" not in item:
                    continue

                for k, v in item['settings'].items():
                    item['settings'][k] = self.pick(v)

                t['tokenColors'].append(item)

        with open(self.dest, "w") as f:
            print("Same theme       : {0}".format(datetime.now().time()))
            json.dump(t, fp=f, indent=4)

    @staticmethod
    def random_color() -> str:
        return "#" + ''.join([ch('0123456789ABCDEF') for j in range(6)])

    @staticmethod
    def read(file):
        _, ext = splitext(file)

        executors = {
            '.yaml': lambda file: yaml.load(file, Loader=yaml.CLoader),
            '.yml': lambda file: yaml.load(file, Loader=yaml.CLoader),
            '.json': lambda file: json.load(file),
        }
        try:
            with open(file, "r") as f:
                return executors.get(ext)(f)
        except BaseException as e:
            print(f"Error reading {file} with {e}")

        return {}


def main(quickMode):
    theme = Theme()
    while True:
        if theme.is_changed():
            theme.generate()
        if quickMode:
            return
        time.sleep(1)


if __name__ == "__main__":
    import sys

    main("--quick" in sys.argv)
