#!/usr/bin/env python3

import sys, json
"""
    Extracts grammars from tm tmLanguage.json files

    ./scripts/grammar php.tmLanguage.json

"""


def traverse(items):
    results = []

    if isinstance(items, list):
        for item in items:
            results += traverse(item)
        return results

    if isinstance(items, dict):
        for k, v in items.items():
            # print(k, v)
            if k == "name" and isinstance(v, str):
                results.append(v)
                continue

            if isinstance(v, list) or isinstance(v, dict):
                results += traverse(v)
                continue

        return results

    return results


def main(grammar):

    with open(grammar, "r") as f:
        data = traverse(json.load(f))

    items = [item for item in sorted(list(set(data)))]
    print("\n".join(items))


if __name__ == "__main__":

    try:
        if len(sys.argv) > 1:
            main(sys.argv[1])
        else:
            exit(
                "Provide path to tmLanguage.json file:\n\t./grammar [tmLanguage.json]"
            )
    except BaseException as e:
        print(e)
