#!/usr/bin/env python3

import json
import sys

import yaml


def convert(src:str, dst:str="stdout"):

    with open(src, 'r') as f:
        data = yaml.safe_load(f)

    if dst == "stdout":
        json.dump(data, sys.stdout, indent=4)
        return

    with open(dst, "w") as f:
        json.dump(data, f, indent=4, sort_keys=False)

if __name__ == "__main__":
    import sys
    convert(*sys.argv[1:])
    # convert()
